### ISSUE TITLE
enhancement 

### ISSUE THREAD

**Issue by akanksha99-rs** [ananyaynkit/Microsoft-Udacity-ML-scholarship#24]
In the this FOLDER https://github.com/ananyaynkit/Microsoft-Udacity-ML-scholarship/tree/master/Notes I would like to share the resources containing notes on basics of ML with everyone

**Comment by palak9** [comment]
@akanksha99-rs that's great! Are you facing any issues while doing it ?

**Comment by akanksha99-rs** [comment]
No, I am not.
Thank you
