### ISSUE TITLE
What is the reason behind the size of the .git folder so big?

### ISSUE THREAD

**Issue by Rezwanul-Haque** [ananyaynkit/Microsoft-Udacity-ML-scholarship#26]
![git folder size](https://user-images.githubusercontent.com/22642254/87793406-0c31d300-c867-11ea-8dc8-3b76052fb621.png)

Repo's content size is 27.1 MB and .git folder size 755.4 MB why?

**Comment by ananyaynkit** [comment]
Thank you for the information. We will surely compress the size with time.

**Comment by palak9** [comment]
@Rezwanul-Haque It is because git stores the history of commits. Previously we had added some folders which were quite heavy but then we had deleted them. Just deleting those folders will not reduce the size of repository, in order to that we'll need to clear the git history. Thanks for informing!
